### ISSUE TITLE
Make size() public or make put() return index of appended element

### ISSUE THREAD

**Issue by pogo19** [mrwilson/java-dirty#4]
In my project, I have several implementations of event log and one of them is based on java-dirty. I also have some indices that point to the log via position/index number. As I add new entry to Store via put(), I would like to get the position of the entry. Or let me get it via size().

Please consider.

**Comment by mrwilson** [comment]
Hi Jan

I agree, exposing size() and returning the index on put() are both useful features - these will both get added soon.

Thanks!

Alex

**Comment by pogo19** [comment]
Alex, thanks for considering my suggestion. I think it may be better to specify size and index with long instead of integer. What do you think?

**Comment by mrwilson** [comment]
The most recent change returns the index of an inserted number on put.

**Comment by pogo19** [comment]
Thanks!
